// <auto-generated />
namespace MunkaidoNyilvantarto.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class CommentCreated_mezo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CommentCreated_mezo));
        
        string IMigrationMetadata.Id
        {
            get { return "201511271841347_CommentCreated_mezo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
